version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/aimpugn.me/
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/start.sh
      timeout: 300
      runas: ubuntu
